---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name : httpd
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes


    - name: install apache2package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Dibian"

    - name: start apache2 service
      service:
        name : apache2
        state: started
      when: ansible_os_family == "Dibian"

    - name: copy index.html
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/htl
        mode: 0666
