---
- name: my test playbook
  hosts: all
  become: true
  tasks: 
   - name: create multiple users
     user: name='{{ item }}' state=present
     with_items:
            - abhi
            - vishal
            - kushi  


